# Generated by Django 4.2.3 on 2023-08-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatorform', '0003_alter_coordinator_address_alter_coordinator_college_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'permissions': (('is_reviewed', 'New Profile!'),)},
        ),
        migrations.AddField(
            model_name='coordinator',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
