# Generated by Django 4.2.3 on 2023-08-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('coordinatorform', '0004_alter_coordinator_options_coordinator_is_reviewed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coOrdinator',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('is_reviewed', 'new profile'),)},
        ),
    ]
