# Generated by Django 4.2.3 on 2023-08-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('coordinatorform', '0005_rename_coordinator_user_alter_user_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Coordinator',
        ),
    ]
