# Generated by Django 4.2.3 on 2023-08-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatorform', '0007_rename_exp_coordinator_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinator',
            old_name='address',
            new_name='peraddress',
        ),
        migrations.RenameField(
            model_name='coordinator',
            old_name='upazila',
            new_name='praddress',
        ),
    ]
