# Generated by Django 4.2.3 on 2023-08-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatorform', '0008_rename_address_coordinator_peraddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='interests',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='skills',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
