# Generated by Django 4.2.3 on 2023-08-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatorform', '0009_coordinator_interests_coordinator_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
