# Generated by Django 4.2.3 on 2023-08-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatorform', '0010_coordinator_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='cpassword',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='picture',
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='college',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='dateofbirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='experience',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='facebook',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='interests',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='nickname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='peraddress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='praddress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='religion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='school',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='skills',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
