# Generated by Django 4.2.3 on 2023-08-13 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatorform', '0011_remove_coordinator_cpassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='picture',
            field=models.FileField(default=django.utils.timezone.now, upload_to='profilepics/'),
            preserve_default=False,
        ),
    ]
