# Generated by Django 4.2.3 on 2023-08-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatorform', '0012_coordinator_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='college',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='dateofbirth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='experience',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='interests',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='peraddress',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profilepics/'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='praddress',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='religion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='skills',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
