# Generated by Django 4.2.3 on 2023-08-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatorform', '0017_alter_coordinator_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profilepics/'),
        ),
    ]
