# Generated by Django 4.2.3 on 2023-08-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatorform', '0018_alter_coordinator_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='instagram',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='linkedin',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='twitter',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='whatsapp',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='facebook',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
    ]
