# Generated by Django 4.2.3 on 2023-08-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatorform', '0019_coordinator_instagram_coordinator_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'permissions': (('is_reviewed', 'new profile'), ('coordinator', 'Permission for viewing administration'))},
        ),
    ]
